package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'ChildProject_Build'
in the project with id = 'ChildProject', and delete the patch script.
*/
create(RelativeId("ChildProject"), BuildType({
    id("ChildProject_Build")
    name = "Build"

    vcs {
        root(RelativeId("ChildProject_HttpsGithubComSocksDevilTeamcityAwsLambdaPluginExampleRefsHeadsMain"))
    }

    triggers {
        trigger {
            type = "vcsTrigger"
        }
    }
}))

