package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.KubernetesCloudProfile
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.kubernetesCloudImage
import jetbrains.buildServer.configs.kotlin.kubernetesCloudProfile
import jetbrains.buildServer.configs.kotlin.projectFeatures.DockerRegistryConnection
import jetbrains.buildServer.configs.kotlin.projectFeatures.HashiCorpVaultConnection
import jetbrains.buildServer.configs.kotlin.projectFeatures.dockerRegistry
import jetbrains.buildServer.configs.kotlin.projectFeatures.hashiCorpVaultConnection
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        remove {
            kubernetesCloudImage {
                id = "PROJECT_EXT_34"
                profileId = "kube-6"
                agentPoolId = "-2"
                agentNamePrefix = "simpledep"
                podSpecification = deploymentTemplate {
                    deploymentName = "simpledep"
                }
                param("imageInstanceLimit", "")
            }
        }
        val feature1 = find<DockerRegistryConnection> {
            dockerRegistry {
                id = "PROJECT_EXT_35"
                name = "Docker Registry"
            }
        }
        feature1.apply {
        }
        val feature2 = find<HashiCorpVaultConnection> {
            hashiCorpVaultConnection {
                id = "hashicorpVaultConnection1"
                name = "HashiCorp Vault"
                url = "http://127.0.0.1:8200"
                authMethod = appRole {
                    roleId = "f3e75c6b-118b-48a1-97fc-6b8a69eb3bc3"
                    secretId = "credentialsJSON:a90c9e97-f71b-4571-bfff-24f0eb0db85b"
                }
                failOnError = false
            }
        }
        feature2.apply {
        }
        val feature3 = find<KubernetesCloudProfile> {
            kubernetesCloudProfile {
                id = "kube-6"
                name = "Dasha Cluster"
                terminateIdleMinutes = 30
                apiServerURL = "https://A51B42A65F7E54005C95A4D353916627.gr7.eu-west-1.eks.amazonaws.com"
                caCertData = "credentialsJSON:4cfb95a6-dd98-454a-98d1-2dd8a28ca6dd"
                authStrategy = eks {
                    accessId = "AKIA5JH2VERVAYHV5RNO"
                    secretKey = "credentialsJSON:5f77bcdc-20b7-4d84-8971-f14dc824a8e7"
                    iamRoleArn = ""
                    clusterName = "tc-dkrupkina-eks-cluster"
                }
            }
        }
        feature3.apply {
            name = "Dasha Cluster"
            terminateIdleMinutes = 30
            apiServerURL = "https://A51B42A65F7E54005C95A4D353916627.gr7.eu-west-1.eks.amazonaws.com"
            caCertData = "credentialsJSON:4cfb95a6-dd98-454a-98d1-2dd8a28ca6dd"
        }
        add {
            kubernetesCloudImage {
                id = "PROJECT_EXT_43"
                profileId = "kube-6"
                agentPoolId = "-2"
                agentNamePrefix = "basic-agent"
                podSpecification = runContainer {
                    dockerImage = "jetbrains/teamcity-agent:2025.07.3-linux"
                }
                param("imageInstanceLimit", "")
            }
        }
    }
}
