package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    params {
        add {
            param("test", "meow")
        }
    }

    features {
        add {
            feature {
                type = "OAuthProvider"
                id = "PROJECT_EXT_7"
                param("displayName", "Kubernetes Connection")
                param("apiServerUrl", "meow")
                param("authStrategy", "unauthorized")
                param("namespace", "meow")
                param("providerType", "KubernetesConnection")
            }
        }
    }
}
