package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'LoadTesting_VcsSettings'
in the project with id = 'LoadTesting', and delete the patch script.
*/
create(RelativeId("LoadTesting"), GitVcsRoot({
    id("LoadTesting_VcsSettings")
    name = "VcsSettings"
    url = "https://github.com/SocksDevil/vcs-settings-executor-load-testing"
    branch = "main"
    authMethod = password {
        userName = "SocksDevil"
        password = "credentialsJSON:2091df62-b0a6-494c-9dd1-b03db1aaf9c6"
    }
}))

